services:
  db_dev:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data:delegated
    networks:
      - backend
  server_api:
    build:
      context: .
      dockerfile: Dockerfile.api.dev
    ports:
      - 3080:3080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PGUSER=postgres
      - PGHOST=db_dev
      - PGPASSWORD=postgres
      - PGDATABASE=test1
      - PGPORT=5432
    volumes:
      - "./api:/api"
      - "./api/node_modules"
    networks:
      - backend
    depends_on:
      - "db_dev"
  frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.my-app.dev
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_DOCKER=true
      - REACT_APP_API_ROUTE=http://server_api:3080/
    volumes:
      - "./my-app:/my-app"
      - "./my-app/node_modules"
    networks:
      - backend
    depends_on:
      - "server_api"

volumes:
  db-data:

networks:
  backend:
