FROM node:12.18.3 AS server-build
WORKDIR /api
COPY api/package*.json ./
RUN npm install
COPY api/server.js ./
COPY api/db-integration ./db-integration
COPY api/controller ./controller
COPY api/my_util ./my_util

EXPOSE 3080

CMD ["npm", "run", "dev"]